version: '3.4'

services:
  minecraftspelunking.presentation.sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: container.minecraftspelunking.presentation.sqlserver
    env_file:
        - .env
    ports: # not actually needed, because the two services are on the same network.
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=${SA_PASSWORD}
  minecraftspelunking.presentation.webserver:
    image: image.minecraftspelunking.presentation.webserver
    container_name: container.minecraftspelunking.presentation.webserver
    env_file:
        - .env
    build:
      context: .
      dockerfile: "./src/4 - presentation/MinecraftSpelunking.Presentation.WebServer/Dockerfile"
    ports: 
      - "${HOST_IP}:${HOST_PORT}:${CONTAINER_PORT}"
